include:
  - project: 'evgeniybudaev/ci-cd'
    ref: main
    file: '.gitlab-ci/.gitlab-ci-main.yml'

build_docker_compose_backend:
  extends: '.build_docker_compose'
  before_script:
    - echo $ENV_FILE
    - cp $ENV_FILE ./app/.env

deploy_docker_compose_backend:
  extends:  '.deploy_docker_compose'
  before_script:
    - echo $ENV_FILE
    - cp $ENV_FILE ./app/.env
