// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: contracts/proto/profiles/profile.proto

package profiles

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Profile_AddProfile_FullMethodName                 = "/protobuf.Profile/AddProfile"
	Profile_UpdateProfile_FullMethodName              = "/protobuf.Profile/UpdateProfile"
	Profile_FreezeProfile_FullMethodName              = "/protobuf.Profile/FreezeProfile"
	Profile_RestoreProfile_FullMethodName             = "/protobuf.Profile/RestoreProfile"
	Profile_DeleteProfile_FullMethodName              = "/protobuf.Profile/DeleteProfile"
	Profile_GetProfileByTelegramUserId_FullMethodName = "/protobuf.Profile/GetProfileByTelegramUserId"
	Profile_GetProfileDetail_FullMethodName           = "/protobuf.Profile/GetProfileDetail"
	Profile_GetProfileShortInfo_FullMethodName        = "/protobuf.Profile/GetProfileShortInfo"
	Profile_GetProfileList_FullMethodName             = "/protobuf.Profile/GetProfileList"
	Profile_GetImageByTelegramUserId_FullMethodName   = "/protobuf.Profile/GetImageByTelegramUserId"
	Profile_GetImageById_FullMethodName               = "/protobuf.Profile/GetImageById"
	Profile_DeleteImage_FullMethodName                = "/protobuf.Profile/DeleteImage"
	Profile_UpdateFilter_FullMethodName               = "/protobuf.Profile/UpdateFilter"
	Profile_AddBlock_FullMethodName                   = "/protobuf.Profile/AddBlock"
	Profile_AddLike_FullMethodName                    = "/protobuf.Profile/AddLike"
	Profile_UpdateLike_FullMethodName                 = "/protobuf.Profile/UpdateLike"
	Profile_AddComplaint_FullMethodName               = "/protobuf.Profile/AddComplaint"
	Profile_UpdateCoordinates_FullMethodName          = "/protobuf.Profile/UpdateCoordinates"
)

// ProfileClient is the client API for Profile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfileClient interface {
	AddProfile(ctx context.Context, in *ProfileAddRequest, opts ...grpc.CallOption) (*ProfileAddResponse, error)
	UpdateProfile(ctx context.Context, in *ProfileUpdateRequest, opts ...grpc.CallOption) (*ProfileByTelegramUserIdResponse, error)
	FreezeProfile(ctx context.Context, in *ProfileFreezeRequest, opts ...grpc.CallOption) (*ProfileFreezeResponse, error)
	RestoreProfile(ctx context.Context, in *ProfileRestoreRequest, opts ...grpc.CallOption) (*ProfileRestoreResponse, error)
	DeleteProfile(ctx context.Context, in *ProfileDeleteRequest, opts ...grpc.CallOption) (*ProfileDeleteResponse, error)
	GetProfileByTelegramUserId(ctx context.Context, in *ProfileGetByTelegramUserIdRequest, opts ...grpc.CallOption) (*ProfileByTelegramUserIdResponse, error)
	GetProfileDetail(ctx context.Context, in *ProfileGetDetailRequest, opts ...grpc.CallOption) (*ProfileDetailResponse, error)
	GetProfileShortInfo(ctx context.Context, in *ProfileGetShortInfoRequest, opts ...grpc.CallOption) (*ProfileShortInfoResponse, error)
	GetProfileList(ctx context.Context, in *ProfileGetListRequest, opts ...grpc.CallOption) (*ProfileListResponse, error)
	GetImageByTelegramUserId(ctx context.Context, in *GetImageByTelegramUserIdRequest, opts ...grpc.CallOption) (*ImageByTelegramUserIdResponse, error)
	GetImageById(ctx context.Context, in *GetImageByIdRequest, opts ...grpc.CallOption) (*ImageResponse, error)
	DeleteImage(ctx context.Context, in *ImageDeleteRequest, opts ...grpc.CallOption) (*ImageDeleteResponse, error)
	UpdateFilter(ctx context.Context, in *FilterUpdateRequest, opts ...grpc.CallOption) (*FilterUpdateResponse, error)
	AddBlock(ctx context.Context, in *BlockAddRequest, opts ...grpc.CallOption) (*BlockAddResponse, error)
	AddLike(ctx context.Context, in *LikeAddRequest, opts ...grpc.CallOption) (*LikeAddResponse, error)
	UpdateLike(ctx context.Context, in *LikeUpdateRequest, opts ...grpc.CallOption) (*LikeUpdateResponse, error)
	AddComplaint(ctx context.Context, in *ComplaintAddRequest, opts ...grpc.CallOption) (*ComplaintAddResponse, error)
	UpdateCoordinates(ctx context.Context, in *NavigatorUpdateRequest, opts ...grpc.CallOption) (*NavigatorUpdateResponse, error)
}

type profileClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileClient(cc grpc.ClientConnInterface) ProfileClient {
	return &profileClient{cc}
}

func (c *profileClient) AddProfile(ctx context.Context, in *ProfileAddRequest, opts ...grpc.CallOption) (*ProfileAddResponse, error) {
	out := new(ProfileAddResponse)
	err := c.cc.Invoke(ctx, Profile_AddProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) UpdateProfile(ctx context.Context, in *ProfileUpdateRequest, opts ...grpc.CallOption) (*ProfileByTelegramUserIdResponse, error) {
	out := new(ProfileByTelegramUserIdResponse)
	err := c.cc.Invoke(ctx, Profile_UpdateProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) FreezeProfile(ctx context.Context, in *ProfileFreezeRequest, opts ...grpc.CallOption) (*ProfileFreezeResponse, error) {
	out := new(ProfileFreezeResponse)
	err := c.cc.Invoke(ctx, Profile_FreezeProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) RestoreProfile(ctx context.Context, in *ProfileRestoreRequest, opts ...grpc.CallOption) (*ProfileRestoreResponse, error) {
	out := new(ProfileRestoreResponse)
	err := c.cc.Invoke(ctx, Profile_RestoreProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) DeleteProfile(ctx context.Context, in *ProfileDeleteRequest, opts ...grpc.CallOption) (*ProfileDeleteResponse, error) {
	out := new(ProfileDeleteResponse)
	err := c.cc.Invoke(ctx, Profile_DeleteProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) GetProfileByTelegramUserId(ctx context.Context, in *ProfileGetByTelegramUserIdRequest, opts ...grpc.CallOption) (*ProfileByTelegramUserIdResponse, error) {
	out := new(ProfileByTelegramUserIdResponse)
	err := c.cc.Invoke(ctx, Profile_GetProfileByTelegramUserId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) GetProfileDetail(ctx context.Context, in *ProfileGetDetailRequest, opts ...grpc.CallOption) (*ProfileDetailResponse, error) {
	out := new(ProfileDetailResponse)
	err := c.cc.Invoke(ctx, Profile_GetProfileDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) GetProfileShortInfo(ctx context.Context, in *ProfileGetShortInfoRequest, opts ...grpc.CallOption) (*ProfileShortInfoResponse, error) {
	out := new(ProfileShortInfoResponse)
	err := c.cc.Invoke(ctx, Profile_GetProfileShortInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) GetProfileList(ctx context.Context, in *ProfileGetListRequest, opts ...grpc.CallOption) (*ProfileListResponse, error) {
	out := new(ProfileListResponse)
	err := c.cc.Invoke(ctx, Profile_GetProfileList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) GetImageByTelegramUserId(ctx context.Context, in *GetImageByTelegramUserIdRequest, opts ...grpc.CallOption) (*ImageByTelegramUserIdResponse, error) {
	out := new(ImageByTelegramUserIdResponse)
	err := c.cc.Invoke(ctx, Profile_GetImageByTelegramUserId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) GetImageById(ctx context.Context, in *GetImageByIdRequest, opts ...grpc.CallOption) (*ImageResponse, error) {
	out := new(ImageResponse)
	err := c.cc.Invoke(ctx, Profile_GetImageById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) DeleteImage(ctx context.Context, in *ImageDeleteRequest, opts ...grpc.CallOption) (*ImageDeleteResponse, error) {
	out := new(ImageDeleteResponse)
	err := c.cc.Invoke(ctx, Profile_DeleteImage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) UpdateFilter(ctx context.Context, in *FilterUpdateRequest, opts ...grpc.CallOption) (*FilterUpdateResponse, error) {
	out := new(FilterUpdateResponse)
	err := c.cc.Invoke(ctx, Profile_UpdateFilter_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) AddBlock(ctx context.Context, in *BlockAddRequest, opts ...grpc.CallOption) (*BlockAddResponse, error) {
	out := new(BlockAddResponse)
	err := c.cc.Invoke(ctx, Profile_AddBlock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) AddLike(ctx context.Context, in *LikeAddRequest, opts ...grpc.CallOption) (*LikeAddResponse, error) {
	out := new(LikeAddResponse)
	err := c.cc.Invoke(ctx, Profile_AddLike_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) UpdateLike(ctx context.Context, in *LikeUpdateRequest, opts ...grpc.CallOption) (*LikeUpdateResponse, error) {
	out := new(LikeUpdateResponse)
	err := c.cc.Invoke(ctx, Profile_UpdateLike_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) AddComplaint(ctx context.Context, in *ComplaintAddRequest, opts ...grpc.CallOption) (*ComplaintAddResponse, error) {
	out := new(ComplaintAddResponse)
	err := c.cc.Invoke(ctx, Profile_AddComplaint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) UpdateCoordinates(ctx context.Context, in *NavigatorUpdateRequest, opts ...grpc.CallOption) (*NavigatorUpdateResponse, error) {
	out := new(NavigatorUpdateResponse)
	err := c.cc.Invoke(ctx, Profile_UpdateCoordinates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServer is the server API for Profile service.
// All implementations must embed UnimplementedProfileServer
// for forward compatibility
type ProfileServer interface {
	AddProfile(context.Context, *ProfileAddRequest) (*ProfileAddResponse, error)
	UpdateProfile(context.Context, *ProfileUpdateRequest) (*ProfileByTelegramUserIdResponse, error)
	FreezeProfile(context.Context, *ProfileFreezeRequest) (*ProfileFreezeResponse, error)
	RestoreProfile(context.Context, *ProfileRestoreRequest) (*ProfileRestoreResponse, error)
	DeleteProfile(context.Context, *ProfileDeleteRequest) (*ProfileDeleteResponse, error)
	GetProfileByTelegramUserId(context.Context, *ProfileGetByTelegramUserIdRequest) (*ProfileByTelegramUserIdResponse, error)
	GetProfileDetail(context.Context, *ProfileGetDetailRequest) (*ProfileDetailResponse, error)
	GetProfileShortInfo(context.Context, *ProfileGetShortInfoRequest) (*ProfileShortInfoResponse, error)
	GetProfileList(context.Context, *ProfileGetListRequest) (*ProfileListResponse, error)
	GetImageByTelegramUserId(context.Context, *GetImageByTelegramUserIdRequest) (*ImageByTelegramUserIdResponse, error)
	GetImageById(context.Context, *GetImageByIdRequest) (*ImageResponse, error)
	DeleteImage(context.Context, *ImageDeleteRequest) (*ImageDeleteResponse, error)
	UpdateFilter(context.Context, *FilterUpdateRequest) (*FilterUpdateResponse, error)
	AddBlock(context.Context, *BlockAddRequest) (*BlockAddResponse, error)
	AddLike(context.Context, *LikeAddRequest) (*LikeAddResponse, error)
	UpdateLike(context.Context, *LikeUpdateRequest) (*LikeUpdateResponse, error)
	AddComplaint(context.Context, *ComplaintAddRequest) (*ComplaintAddResponse, error)
	UpdateCoordinates(context.Context, *NavigatorUpdateRequest) (*NavigatorUpdateResponse, error)
	mustEmbedUnimplementedProfileServer()
}

// UnimplementedProfileServer must be embedded to have forward compatible implementations.
type UnimplementedProfileServer struct {
}

func (UnimplementedProfileServer) AddProfile(context.Context, *ProfileAddRequest) (*ProfileAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProfile not implemented")
}
func (UnimplementedProfileServer) UpdateProfile(context.Context, *ProfileUpdateRequest) (*ProfileByTelegramUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedProfileServer) FreezeProfile(context.Context, *ProfileFreezeRequest) (*ProfileFreezeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FreezeProfile not implemented")
}
func (UnimplementedProfileServer) RestoreProfile(context.Context, *ProfileRestoreRequest) (*ProfileRestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreProfile not implemented")
}
func (UnimplementedProfileServer) DeleteProfile(context.Context, *ProfileDeleteRequest) (*ProfileDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProfile not implemented")
}
func (UnimplementedProfileServer) GetProfileByTelegramUserId(context.Context, *ProfileGetByTelegramUserIdRequest) (*ProfileByTelegramUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfileByTelegramUserId not implemented")
}
func (UnimplementedProfileServer) GetProfileDetail(context.Context, *ProfileGetDetailRequest) (*ProfileDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfileDetail not implemented")
}
func (UnimplementedProfileServer) GetProfileShortInfo(context.Context, *ProfileGetShortInfoRequest) (*ProfileShortInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfileShortInfo not implemented")
}
func (UnimplementedProfileServer) GetProfileList(context.Context, *ProfileGetListRequest) (*ProfileListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfileList not implemented")
}
func (UnimplementedProfileServer) GetImageByTelegramUserId(context.Context, *GetImageByTelegramUserIdRequest) (*ImageByTelegramUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImageByTelegramUserId not implemented")
}
func (UnimplementedProfileServer) GetImageById(context.Context, *GetImageByIdRequest) (*ImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImageById not implemented")
}
func (UnimplementedProfileServer) DeleteImage(context.Context, *ImageDeleteRequest) (*ImageDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteImage not implemented")
}
func (UnimplementedProfileServer) UpdateFilter(context.Context, *FilterUpdateRequest) (*FilterUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFilter not implemented")
}
func (UnimplementedProfileServer) AddBlock(context.Context, *BlockAddRequest) (*BlockAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBlock not implemented")
}
func (UnimplementedProfileServer) AddLike(context.Context, *LikeAddRequest) (*LikeAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLike not implemented")
}
func (UnimplementedProfileServer) UpdateLike(context.Context, *LikeUpdateRequest) (*LikeUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLike not implemented")
}
func (UnimplementedProfileServer) AddComplaint(context.Context, *ComplaintAddRequest) (*ComplaintAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddComplaint not implemented")
}
func (UnimplementedProfileServer) UpdateCoordinates(context.Context, *NavigatorUpdateRequest) (*NavigatorUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCoordinates not implemented")
}
func (UnimplementedProfileServer) mustEmbedUnimplementedProfileServer() {}

// UnsafeProfileServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfileServer will
// result in compilation errors.
type UnsafeProfileServer interface {
	mustEmbedUnimplementedProfileServer()
}

func RegisterProfileServer(s grpc.ServiceRegistrar, srv ProfileServer) {
	s.RegisterService(&Profile_ServiceDesc, srv)
}

func _Profile_AddProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).AddProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Profile_AddProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).AddProfile(ctx, req.(*ProfileAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Profile_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).UpdateProfile(ctx, req.(*ProfileUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_FreezeProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileFreezeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).FreezeProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Profile_FreezeProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).FreezeProfile(ctx, req.(*ProfileFreezeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_RestoreProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).RestoreProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Profile_RestoreProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).RestoreProfile(ctx, req.(*ProfileRestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_DeleteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).DeleteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Profile_DeleteProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).DeleteProfile(ctx, req.(*ProfileDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_GetProfileByTelegramUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileGetByTelegramUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).GetProfileByTelegramUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Profile_GetProfileByTelegramUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).GetProfileByTelegramUserId(ctx, req.(*ProfileGetByTelegramUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_GetProfileDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileGetDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).GetProfileDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Profile_GetProfileDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).GetProfileDetail(ctx, req.(*ProfileGetDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_GetProfileShortInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileGetShortInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).GetProfileShortInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Profile_GetProfileShortInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).GetProfileShortInfo(ctx, req.(*ProfileGetShortInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_GetProfileList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileGetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).GetProfileList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Profile_GetProfileList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).GetProfileList(ctx, req.(*ProfileGetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_GetImageByTelegramUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImageByTelegramUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).GetImageByTelegramUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Profile_GetImageByTelegramUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).GetImageByTelegramUserId(ctx, req.(*GetImageByTelegramUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_GetImageById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImageByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).GetImageById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Profile_GetImageById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).GetImageById(ctx, req.(*GetImageByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_DeleteImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).DeleteImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Profile_DeleteImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).DeleteImage(ctx, req.(*ImageDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_UpdateFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).UpdateFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Profile_UpdateFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).UpdateFilter(ctx, req.(*FilterUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_AddBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).AddBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Profile_AddBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).AddBlock(ctx, req.(*BlockAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_AddLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).AddLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Profile_AddLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).AddLike(ctx, req.(*LikeAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_UpdateLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).UpdateLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Profile_UpdateLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).UpdateLike(ctx, req.(*LikeUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_AddComplaint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComplaintAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).AddComplaint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Profile_AddComplaint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).AddComplaint(ctx, req.(*ComplaintAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_UpdateCoordinates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NavigatorUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).UpdateCoordinates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Profile_UpdateCoordinates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).UpdateCoordinates(ctx, req.(*NavigatorUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Profile_ServiceDesc is the grpc.ServiceDesc for Profile service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Profile_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Profile",
	HandlerType: (*ProfileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddProfile",
			Handler:    _Profile_AddProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _Profile_UpdateProfile_Handler,
		},
		{
			MethodName: "FreezeProfile",
			Handler:    _Profile_FreezeProfile_Handler,
		},
		{
			MethodName: "RestoreProfile",
			Handler:    _Profile_RestoreProfile_Handler,
		},
		{
			MethodName: "DeleteProfile",
			Handler:    _Profile_DeleteProfile_Handler,
		},
		{
			MethodName: "GetProfileByTelegramUserId",
			Handler:    _Profile_GetProfileByTelegramUserId_Handler,
		},
		{
			MethodName: "GetProfileDetail",
			Handler:    _Profile_GetProfileDetail_Handler,
		},
		{
			MethodName: "GetProfileShortInfo",
			Handler:    _Profile_GetProfileShortInfo_Handler,
		},
		{
			MethodName: "GetProfileList",
			Handler:    _Profile_GetProfileList_Handler,
		},
		{
			MethodName: "GetImageByTelegramUserId",
			Handler:    _Profile_GetImageByTelegramUserId_Handler,
		},
		{
			MethodName: "GetImageById",
			Handler:    _Profile_GetImageById_Handler,
		},
		{
			MethodName: "DeleteImage",
			Handler:    _Profile_DeleteImage_Handler,
		},
		{
			MethodName: "UpdateFilter",
			Handler:    _Profile_UpdateFilter_Handler,
		},
		{
			MethodName: "AddBlock",
			Handler:    _Profile_AddBlock_Handler,
		},
		{
			MethodName: "AddLike",
			Handler:    _Profile_AddLike_Handler,
		},
		{
			MethodName: "UpdateLike",
			Handler:    _Profile_UpdateLike_Handler,
		},
		{
			MethodName: "AddComplaint",
			Handler:    _Profile_AddComplaint_Handler,
		},
		{
			MethodName: "UpdateCoordinates",
			Handler:    _Profile_UpdateCoordinates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contracts/proto/profiles/profile.proto",
}
